### ISSUE TITLE
Plugin does not fold className, when using curly braces

### ISSUE THREAD

**Issue by sebkasanzew** [stivoat/tailwind-fold#1]
The [current regex](https://github.com/stivoat/tailwind-fold/blob/b35db104d0d5849d6341d82b36a09ff006f73427/src/decorator.ts#L14) at this line only matches `className`s where strings are assigned

### Example:

Folds properly:
```typescriptreact
<button className="btn btn-primary" onClick={handleSignOut}>
    Logout
</button>
```
<br/>

Does not Fold:
```typescriptreact
<button className={"btn btn-primary"} onClick={handleSignOut}>
    Logout
</button>
```

### Expected:
The plugin should also fold `className`s that use `{}`

If no one has the time to implement this feature, I could maybe open a PR next week. 🙂

**Comment by stivoat** [comment]
Thanks for pointing this out!
I just updated the regex (#1). Another set of eyes on it would be ideal before publishing it to the marketplace.

**Comment by sebkasanzew** [comment]
I added some comments inline in the PR: https://github.com/stivoat/tailwind-fold/commit/95e82dfa975adbb3556e17aabef1ba7d4476b9d0#r96470972
