### ISSUE TITLE
Icon resolution low on HiDPI screens

### ISSUE THREAD

**Issue by itsmingjie** [stivoat/tailwind-fold#13]
See screenshot below. Using a MacBook Pro with Retina screen, resolution 3456 x 2234 Retina. Will it cause any issue if the icon is slightly higher resolution? Or, could it possibly be rendered as an SVG?

![32980](https://user-images.githubusercontent.com/13333578/232623423-4d4cdd6b-29c1-4408-a887-bde4ae238eb5.png)

**Comment by diamondback15** [comment]
This is driving me crazy as well!
