### ISSUE TITLE
Can I add a custom regEx?

### ISSUE THREAD

**Issue by Hansanghyeon** [stivoat/tailwind-fold#17]
I am using twin.macro in react so the value of `tw` property is always tailwind style. However, you cannot add regEx separately.

```js
// example
const App = () => <div tw="flex flex-wrap" />
```

It would be great if this was added. thank you

**Comment by Etsi0** [comment]
[Class Collapse](https://marketplace.visualstudio.com/items?itemName=Etsi0.class-collapse) and [Inline Fold](https://marketplace.visualstudio.com/items?itemName=moalamri.inline-fold) are both offering the feature you're looking for if you prefer not to wait for Tailwind Fold to add this feature.
