### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by voodoomsr** [stivoat/tailwind-fold#19]
Hi guys, I can't make it work for this scenario

``` 
<div 
      class="max-w-[130rem] grid grid-cols-[1fr_1fr] items-center gap-[9.6rem] mx-auto my-0 px-[3.2rem] py-0
      wideDesktop:max-w-[120rem]
      desktop:px-[3.2rem] desktop:py-0
      tablet:grid-cols-[1fr] tablet:justify-center tablet:gap-[6.4rem] tablet:px-32 tablet:py-0
      mobile:py-0 mobile:px-[3.2rem]">
```

Is there anything I need to set or change in order I could fold that multiline class attribute?

This is how it looks:
![image](https://github.com/stivoat/tailwind-fold/assets/26122666/b8ed4411-ff4b-47c9-829d-69adbea38ace)

**Comment by magalhaespaulo** [comment]
Please!
<img width="347" alt="Screenshot 2023-11-15 at 12 14 50" src="https://github.com/stivoat/tailwind-fold/assets/2568820/ea3930bb-f7fe-4d16-905d-5932331094bb">
