### ISSUE TITLE
Ability to hide classes defined using curly braces

### ISSUE THREAD

**Issue by milindgoel15** [stivoat/tailwind-fold#30]
Sometimes we have to define classes using curly braces instead of just quotes when we have to merge some classes that are conditionally rendered. For example:

```tsx

className={`some class here ${some condition based class here}`}
OR
className={cn(
               "some class here",
               some condition based class here
            )}

```

The first one works randomly. I think if there are lots of classes and the prettier has moved the ending bracket to next line, the extension fails to fold. 

example:
![image](https://github.com/stivoat/tailwind-fold/assets/45682747/e4a818a9-1800-485b-90dd-5c848de96fea)

**Comment by Albin0825** [comment]
+1
it would be nice if they could make it fold into something like this:
```jsx
className={...}
```

**Comment by Albin0825** [comment]
i think this would fix it:
```ts
/(class|className)=(['"`]|{)(.*?)(\2|})/g
```
