### ISSUE TITLE
Enable folding only for long class attributes "tailwind-fold.minClassLenght"

### ISSUE THREAD

**Issue by hanc2006** [stivoat/tailwind-fold#7]
It would be nice to be able to control when to fold a class attributes based it length. For example, activate folding only when class attribute length is greater than some value. You could add a new extension setting like the following:

`tailwind-fold.minClassLenght`: Enable the class attribute folding only when the class attribute length is greater than the specified setting.

**Comment by stivoat** [comment]
Implemented in #21
